### PR TITLE
Vectors

### PR DESCRIPTION
**Pull request by chikeabuah**

### CODE REVIEW

**Comment by chikeabuah** [comment]
probably because the bullets are dynamically allocated

**Comment by jeapostrophe** [comment]
I looked at the code. Here's a patch that reindents, changes a few functions, then notates where you still have allocation. I think you need to use your entity representation better so you don't need to create intermediate lists at all. For instance, `name?` on line 69 should be able to just check if that component is enabled via the index.

[jay.txt](https://github.com/chikeabuah/recess/files/2485234/jay.txt)

**Comment by chikeabuah** [comment]
got it, thank you!

**Comment by chikeabuah** [comment]
@jeapostrophe the most recent commit produced a performance boost of +~20fps

**Comment by jeapostrophe** [comment]
Boom! That's awesome

**Comment by chikeabuah** [comment]
currently pushing 50 fps

**Pull request merged**
